name: QuizMaker
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cool_alert: ^1.1.0
  clickable_list_wheel_view: ^0.0.4
  animated_page_reveal: ^1.0.0
  stylish_bottom_bar: ^0.0.2
  cupertino_icons: ^1.0.3
  lint: ^1.0.0
  bloc: ^7.1.0
  cached_network_image: ^3.1.0
  cloud_firestore: ^2.5.2
  equatable: ^2.0.3
  firebase_auth: ^3.1.1
  firebase_core: ^1.6.0
  firebase_storage: ^10.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  flutter_facebook_auth: ^3.5.1
  flutter_hooks: ^0.18.0
  google_fonts: ^2.1.0
  google_sign_in: 5.0.2
  image_picker: ^0.8.4
  intl: ^0.17.0
  page_indicator: ^0.4.1
  path: ^1.8.0

dev_dependencies:
  flutter_native_splash: ^1.2.4
  flutter_launcher_icons: "^0.9.2"
  bloc_test: ^8.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter_native_splash:

  color: "#ffffff"

  image: assets/images/launch_image.png

  web: false
